# Generated by Django 5.1.7 on 2025-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penugasandataset",
            name="status",
            field=models.CharField(
                choices=[
                    ("Assigned", "Assigned"),
                    ("Accepted", "Accepted"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Assigned",
                max_length=50,
            ),
        ),
    ]
