# Generated by Django 5.1.7 on 2025-08-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotator", "0002_alter_penugasandataset_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="gambar",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="penugasandataset",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="segmentasi",
            name="gambar",
        ),
        migrations.RemoveField(
            model_name="subkategorilabel",
            name="kategori",
        ),
        migrations.RemoveField(
            model_name="penugasandataset",
            name="annotator",
        ),
        migrations.RemoveField(
            model_name="poinsegmentasi",
            name="segmentasi",
        ),
        migrations.RemoveField(
            model_name="profilejob",
            name="user",
        ),
        migrations.RemoveField(
            model_name="segmentasi",
            name="annotator",
        ),
        migrations.RemoveField(
            model_name="segmentasi",
            name="sub_kategori_label",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Dataset",
        ),
        migrations.DeleteModel(
            name="Gambar",
        ),
        migrations.DeleteModel(
            name="Kategori",
        ),
        migrations.DeleteModel(
            name="PenugasanDataset",
        ),
        migrations.DeleteModel(
            name="PoinSegmentasi",
        ),
        migrations.DeleteModel(
            name="ProfileJob",
        ),
        migrations.DeleteModel(
            name="Segmentasi",
        ),
        migrations.DeleteModel(
            name="SubKategoriLabel",
        ),
    ]
