# Generated by Django 5.2.3 on 2026-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('guest', 'Guest'), ('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('member', 'Member')], default='guest', max_length=20),
        ),
    ]
