# Generated by Django 5.2.3 on 2026-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_jobprofile_status_in_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='status',
            field=models.CharField(choices=[('not_assign', 'Not Assigned'), ('in_progress', 'In Progress'), ('finish', 'Finished'), ('in_review', 'In Review')], default='not_assign', max_length=20),
        ),
    ]
