# Generated by Django 5.2.3 on 2026-07-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_dataset_annotation_type_dataset_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('guest', 'Guest'), ('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('member', 'Member'), ('komisi', 'Komisi')], default='guest', max_length=20),
        ),
    ]
