# Generated by Django 5.2.3 on 2026-07-05 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='komisi_approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status persetujuan admin untuk akun komisi. Hanya relevan jika role=komisi.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='takedown_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='taken_down_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='taken_down_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_down_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status_publikasi',
            field=models.CharField(choices=[('private', 'Private'), ('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('taken_down', 'Taken Down')], default='private', max_length=20),
        ),
    ]
